blog/urls.py
from django.conf.urls import url 

from .views import index, add_blog, delete_blog, update_blog, view_blog
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'add_blog$', add_blog, name='add-blog'), 
    url(r'^delete_blog/(?P<blog_id>\d+)$', delete_blog, name='delete-blog'),
    url(r'^update_blog/(?P<blog_id>\d+)$', update_blog, name='update-blog'),
    url(r'^view_blog/(?P<blog_id>\d+)$', view_blog, name='view-blog'),
]

blogs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('blog.urls', 'blog'), namespace="blog")),
   
]  

blog/models.py
from django.db import models

# Create your models here.
class blog(models.Model):
    name = models.CharField(verbose_name="Blog name", max_length=200)
    content = models.CharField(verbose_name="Blog content", max_length=5000000)
    comment = models.CharField(verbose_name="Blog comment", max_length=200, default="")
    author = models.CharField(verbose_name="Blog author", max_length= 30, default="")

def __str__(self):
        return "%s" %self.name

blog/forms.py
from django import forms
from django.db.models import fields
from django.forms.widgets import Textarea
from .models import blog

class BlogForm(forms.ModelForm):
    class Meta: 
        model = blog
        fields = "name","content","author","comment"
        widgets = {
            'content': Textarea()
        }

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import blog
from django.urls import reverse_lazy
from .forms import BlogForm



# Create your views here.

def index(request):
    template = 'index.html'
    blogs = blog.objects.all()
    context = {
         'blogs': blogs,
    }
    return render(request, template, context)

def add_blog(request):
	template = "add_blog.html"

	if request.method == "POST":
		form = BlogForm(request.POST)
		if form.is_valid():
			form.save()
		return HttpResponseRedirect(reverse_lazy('blog:index'))
	else:
		context = {
			'blog_form': BlogForm(),
		}
		return render(request, template, context)

def delete_blog(request, blog_id):
    blogs = blog.objects.get(id=int(blog_id))
    blogs.delete()
    return HttpResponseRedirect(reverse_lazy('blog:index'))

def update_blog(request, blog_id):
	template = "update_blog.html"
	blogs = blog.objects.get(id=int(blog_id))

	if request.method == "POST":
		form = BlogForm(request.POST, instance=blogs)
		if form.is_valid():
			form.save()
		return HttpResponseRedirect(reverse_lazy('blog:index'))
	else:
		context = {
			'blog_form':BlogForm(instance=blogs),
		}
		return render(request, template, context)

def view_blog(request,blog_id):
	template ="content.html"
	blogs = blog.objects.filter(id=blog_id)
	context = {
        'blogs':blogs,
    }
	return render(request,template,context)

templates/add_blog.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>

	<style type="text/css">
	body {
        background-color: #E6E6E6;
    }

	</style>
	<body>
		<!--
		<h1>Blogs - Add blog</h1>
		<form role="form" action="" method="POST">
		    {% csrf_token %} 
			<table class="table table-bordered table-striped">
				<tbody>
					<tr>
						<th>Name</th>
						<th>{{ blog_form.name }}</th>
					</tr>
					<tr>
						<th>Content</th>
						<th>{{ blog_form.content }}</th>
					</tr>
				</tbody>
			</table>
			<button type="submit" class="btn btn-success">Save</button>
		</form> -->

		

		<div class="bg-white container p-5  pt-2 mt-5">
			<!-- Title -->
			<h1 class="text-center title">Blog - Add blog</h1>
	
	
	
			<div class="row mt-5">
				<div class="text-justify col ">
					<form role="form" action="" method="POST">
						{% csrf_token %} 
						<table class="table table-bordered table-striped">
							<tbody>
								<tr>
									<th>Name</th>
									<th>{{ blog_form.name }}</th>
								</tr>
								<tr>
									<th>Content</th>
									<th>{{ blog_form.content }}</th>
								</tr>
                                <tr>
									<th>Author</th>
									<th>{{ blog_form.author }}</th>
								</tr>
								<tr>
									<th>Comment</th>
									<th>{{ blog_form.comment}}</th>
								</tr>
								
							</tbody>
						</table>
						<button type="submit" class="btn btn-success">Save</button>
					</form>
				</div>	
			</div>
		</div>
	</body>
</html>

templates/add_comment.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>

	<style type="text/css">
	body {
        background-color: #E6E6E6;
    }

	</style>
	<body>
	
			<h1 class="text-center title">Add Comment</h1>
	
	
	
			<div class="row mt-5">
				<div class="text-justify col ">
					<form role="form" action="" method="POST">
						{% csrf_token %} 
						<table class="table table-bordered table-striped">
							<tbody>
								<tr>
									<th>Comment</th>
									<th>{{ blog_form.comment}}</th>
								</tr>
								
							</tbody>
						</table>
						<button type="submit" class="btn btn-success">Save</button>
					</form>
				</div>	
			</div>
		</div>
	</body>
</html>

templates/index.html
<!DOCTYPE html>
<!-- Created by CodingLab |www.youtube.com/CodingLabYT-->
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <title>P2E Games</title>
    <link rel="icon" href="https://image.flaticon.com/icons/png/512/1465/1465677.png">
    <!-- Boxicons CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300&display=swap" rel="stylesheet">
    <!-- BOOTSTRAP LINK -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


    <!-- ROBOTO SLAB -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Mono&family=Roboto+Slab&display=swap"
        rel="stylesheet">
    <!-- font-family: 'Noto Sans Mono', monospace; -->


</head>
<style type="text/css">
    body {
        background-color: #E6E6E6;
    }

    .title {

        font-family: 'Roboto Slab', serif
    }

    .flex-container {
        display: flex;
        flex-wrap: wrap;

    }

    .flex-item {
        flex-grow: 8;
        margin-top: 15px;
        border: 0.01em ridge black;
    }

    .teamDiv {
        border-radius: 3px;
        background: #EDD83D;
        box-shadow: 5px 5px 10px #242323,
            -5px -5px 10px #EBEBD3;
    }

    h4 {
        color: black;
        font-size: 15px;
        font-family: 'Noto Sans JP', sans-serif;
    }


    /*SEARCH BAR*/

    .box {

        width: 900px;
        height: 40px;
        background-color: white;
        border: 0.001em solid black;
        border-radius: 30px;
        display: flex;
        align-items: center;
        padding: 20px;

    }

    .box>i {

        font-size: 20px;
        color: black;


    }

    .box>input {

        flex: 1;
        height: 40px;
        border: none;
        outline: none;
        font-size: 18px;
        padding-left: 10px;

    }

    a, a:hover {
        text-decoration: none;
        color: #E6E6E6;
    }
    tr {
        margin-top: 40px;
        margin-bottom: 70px;
    }
</style>

<body>

    <h1 class="text-center pt-2 mt-5 title">PLAY TO EARN GAMES</h1>
    <!-- Search and add button -->
    <div class="container pt-3 mt-5">
        <div class="row">
            <div class="col input-group">
                <div class="col box">
                    <i class="fa fa-search" aria-hidden="true"></i>
                    <input type="search" name="search">

                </div>

                <div class="ml-2 mr-3">
                    <button type="button" class="btn btn-md btn-success"> <a href="{% url 'blog:add-blog' %}"> Add Blog
                        </a></button>
                </div>
            </div>
        </div>
    </div>

    <!-- list of p2e games -->
    
    <div class="container flex-container mt-4">  
        {% for blog in blogs %}  
        <div class="flex-item teamDiv mr-3 p-3">
           
           <!-- Game name -->
           <h4 class="text-center">{{ blog.name }}</h4>
           <h6 class="text-center"> - {{ blog.author }}</h6>
           <a href="{% url 'blog:view-blog' blog.id %}" class="btn btn-primary ">View</a>
           <a href="{% url 'blog:update-blog' blog.id %}" class="btn btn-success ">Update</a>
           <a href="{% url 'blog:delete-blog' blog.id %}" class="btn btn-danger ">Delete</a>
       

       </div>
       {% empty %} 
            <h4 class="text-center">NO BLOGS YET.</h4>
        {% endfor %}
    </div> 
   


    <!-- <table class="container mt-4">

        <tr>
            <td class="teamDiv p-3">
                {% for blog in blogs %}
                <h4 class="text-center">{{ blog.name }}</h4>
                <h4 class="text-justify">{{ blog.content }}</h4>

                <div class="btn-group btn-group-md">
                   
                </div>
                {% empty %}

                <h4 class="text-center">No blogs yet.</h4>

                {% endfor %}
            </td>
        </tr> <br>
    </table> -->

</body>

</html>

templates/update_blog.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
    <title>Update</title>
	<style type="text/css">
	body {
        background-color: #E6E6E6;
    }

	</style>
	<body>
		<div class="bg-white container p-5  pt-2 mt-5">
			<!-- Title -->
			<h1 class="text-center title">Blog - Update blog</h1>
			<div class="row mt-5">
				<div class="text-justify col ">
					<form role="form" action="" method="POST">
						{% csrf_token %} 
						<table class="table table-bordered table-striped">
							<tbody>
								<tr>
									<th>Name</th>
									<th>{{ blog_form.name }}</th>
								</tr>
								<tr>
									<th>Content</th>
									<th>{{ blog_form.content }}</th>
								</tr>
                                <tr>
									<th>Author</th>
									<th>{{ blog_form.author }}</th>
								</tr>
							</tbody>
						</table>
						<button type="submit" class="btn btn-success">Save</button>
					</form>
				</div>	
			</div>
		</div>
	</body>
</html>